server:
  port: 8090
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: MOCK-SERVICE-RATE-LIMIT
          uri: lb://MOCK-SERVICE/rate
          predicates:
            - Path=/MOCK-SERVICE-RATE/**
          filters:
            - RewritePath=/MOCK-SERVICE-RATE, /
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@SimpleClientAddressResolver}"
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      database: 1
      password: password

logging:
  level:
    web: debug

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8089/eureka}
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  jwt:
    app-name: api-gateway
    public-key: ${PUBLIC-KEY:classpath:public-key.pem}