server:
  port: 8090
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      database: 1
      password: password

logging:
  level:
    web: debug

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8089/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  jwt:
    app-name: api-gateway
    public-key: ${PUBLIC-KEY:classpath:public-key.pem}