server:
  port: 8090
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: MOCK-SERVICE-RATE-LIMIT
          uri: lb://MOCK-SERVICE/rate
          predicates:
            - Path=MOCK-SERVICE-RATE/rate
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@UserKeyResolver}"
                rate-limiter:
                  type: InMemory
                  capacity: 10
                  replenishRate: 10

logging:
  level:
    web: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"