server:
  port: 8090
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: MOCK-SERVICE-RATE-LIMIT
          uri: lb://MOCK-SERVICE/rate
          predicates:
            - Path=/MOCK-SERVICE-RATE/rate/**
          filters:
            - RewritePath=/MOCK-SERVICE-RATE/rate, /rate
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedToken: 1
                key-resolver: "#{@SimpleClientAddressResolver}"
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      password: password

logging:
  level:
    web: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"