server:
  port: 8090
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

logging:
  level:
    web: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"