server:
  port: 8082

spring:
  application:
    name: IDENTITY-SERVICE

application:
  jwt:
    app-name: api-gateway
    private-key: ${PRIVATE-KEY:classpath:private-key.pem}
    public-key: ${PUBLIC-KEY:classpath:public-key.pem}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8089/eureka}
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}